// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqgUKk-pra1uMDl4bBkzFyxGytc0_6YQk',
    appId: '1:442978295899:web:02c5fd2257c9601cecdf7e',
    messagingSenderId: '442978295899',
    projectId: 'delta-ebd4f',
    authDomain: 'delta-ebd4f.firebaseapp.com',
    databaseURL: 'https://delta-ebd4f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'delta-ebd4f.firebasestorage.app',
    measurementId: 'G-LJ5SYTHC9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOwYd9mtiNl_f0v00mEn4kZzIn3yyFU3c',
    appId: '1:442978295899:android:61fe99dba4138097ecdf7e',
    messagingSenderId: '442978295899',
    projectId: 'delta-ebd4f',
    databaseURL: 'https://delta-ebd4f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'delta-ebd4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVt4Gk_4jgCTsGtCnEAbNyjyLDD3dDh2g',
    appId: '1:442978295899:ios:cf604f27efb7e05aecdf7e',
    messagingSenderId: '442978295899',
    projectId: 'delta-ebd4f',
    databaseURL: 'https://delta-ebd4f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'delta-ebd4f.firebasestorage.app',
    iosBundleId: 'com.example.youtubeTuto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVt4Gk_4jgCTsGtCnEAbNyjyLDD3dDh2g',
    appId: '1:442978295899:ios:cf604f27efb7e05aecdf7e',
    messagingSenderId: '442978295899',
    projectId: 'delta-ebd4f',
    databaseURL: 'https://delta-ebd4f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'delta-ebd4f.firebasestorage.app',
    iosBundleId: 'com.example.youtubeTuto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqgUKk-pra1uMDl4bBkzFyxGytc0_6YQk',
    appId: '1:442978295899:web:b644cb70a65a7e35ecdf7e',
    messagingSenderId: '442978295899',
    projectId: 'delta-ebd4f',
    authDomain: 'delta-ebd4f.firebaseapp.com',
    databaseURL: 'https://delta-ebd4f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'delta-ebd4f.firebasestorage.app',
    measurementId: 'G-VJYTM8EYHW',
  );

}